if (CSICS_USE_UHD)
    set(CMAKE_FIND_PACKAGE_PREFER_CONFIG ON)
    find_package(UHD)
    if (NOT UHD_FOUND)
        message(WARNING "UHD library not found but CSICS_USE_UHD is ON.")
    else()
        add_library(uhd INTERFACE)
        target_include_directories(uhd INTERFACE ${UHD_INCLUDE_DIRS})
        target_link_libraries(uhd INTERFACE ${UHD_LIBRARIES})
        set(CSICS_USE_UHD ON)
        set(UHD_FOUND TRUE)
        list(APPEND CSICS_COMPILE_DEFINITIONS CSICS_USE_UHD)
        if (CSICS_UHD_VENDORED)
            message(STATUS "Using vendored UHD library.")
        else()
            message(STATUS "Using system-installed UHD library.")
        endif()
    endif()
endif()

if (CSICS_USE_ZLIB)
    find_package(ZLIB)
    if (NOT ZLIB_FOUND)
        find_library(ZLIB_LIBRARIES zlib)
        if (ZLIB_LIBRARIES)
            set(ZLIB_FOUND TRUE)
        else()
            message(WARNING "ZLIB library not found but CSICS_USE_ZLIB is ON.")
        endif()
    endif()
    if(ZLIB_FOUND)
        add_library(zlib INTERFACE)
        target_include_directories(zlib INTERFACE ${ZLIB_INCLUDE_DIRS})
        target_link_libraries(zlib INTERFACE ${ZLIB_LIBRARIES})
        set(CSICS_USE_ZLIB ON)
        message(STATUS "Using ZLIB compression support.")
        list(APPEND CSICS_COMPILE_DEFINITIONS CSICS_USE_ZLIB)
    endif()
endif()

if (CSICS_USE_ZSTD)
    find_package(Zstd)
    if (NOT ZSTD_FOUND)
        find_library(ZSTD_LIBRARIES zstd)
        if (ZSTD_LIBRARIES)
            set(ZSTD_FOUND TRUE)
        else()
            message(WARNING "ZSTD library not found but CSICS_USE_ZSTD is ON.")
        endif()
    endif()
    if (ZSTD_FOUND)
        add_library(zstd INTERFACE)
        target_include_directories(zstd INTERFACE ${ZSTD_INCLUDE_DIRS})
        target_link_libraries(zstd INTERFACE ${ZSTD_LIBRARIES})
        set(CSICS_USE_ZSTD ON)
        message(STATUS "Using ZSTD compression support.")
        list(APPEND CSICS_COMPILE_DEFINITIONS CSICS_USE_ZSTD)
    endif()
endif()

