
find_package(UHD)
if (UHD_FOUND)
    message(STATUS "Using system UHD library")
    add_library(uhd INTERFACE)
    target_include_directories(uhd INTERFACE ${UHD_INCLUDE_DIRS})
    target_link_libraries(uhd INTERFACE ${UHD_LIBRARIES})
    set(CSICS_USE_UHD ON)
else()
    set(CSICS_USE_UHD OFF)
    message(WARNING "System UHD library not found")
endif()
